### ISSUE TITLE
npm start is not working

### ISSUE THREAD

**Issue by JBaczuk** [JBaczuk/crypto-dashboard#9]
```
dark-knight:crypto-dashboard-master jbaczuk$ PORT=8000 npm start

> crypto-dashboard@0.1.0 prestart /Users/jbaczuk/Downloads/crypto-dashboard-master
> npm run -s build

src/api/balances.js -> dist/api/balances.js
src/api/facets.js -> dist/api/facets.js
src/api/index.js -> dist/api/index.js
src/db.js -> dist/db.js
src/index.js -> dist/index.js
src/lib/util.js -> dist/lib/util.js
src/middleware/index.js -> dist/middleware/index.js
src/models/balances.js -> dist/models/balances.js
src/models/exchange_auth.js -> dist/models/exchange_auth.js
src/models/facets.js -> dist/models/facets.js
src/models/test_balances.js -> dist/models/test_balances.js

> crypto-dashboard@0.1.0 start /Users/jbaczuk/Downloads/crypto-dashboard-master
> node dist

/Users/jbaczuk/Downloads/crypto-dashboard-master/dist/models/balances.js:90
            var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee() {
                                                       ^

ReferenceError: regeneratorRuntime is not defined
    at /Users/jbaczuk/Downloads/crypto-dashboard-master/dist/models/balances.js:90:56
    at /Users/jbaczuk/Downloads/crypto-dashboard-master/dist/models/balances.js:123:10
    at Object.<anonymous> (/Users/jbaczuk/Downloads/crypto-dashboard-master/dist/models/balances.js:286:2)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! crypto-dashboard@0.1.0 start: `node dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the crypto-dashboard@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jbaczuk/.npm/_logs/2017-12-08T17_09_45_929Z-debug.log
```

**Comment by JBaczuk** [comment]
In order to use asynchronous functions, you have to use `babel-polyfill` npm package and import it into the file in which you are using async functions.
